[tool.poetry]
name = "agilecode_test_tools"
version = "0.4.0"
description = "Package contains reusable code for api and unit tests"
authors = ["Vladyslav Rylov <vladislav.rylov@agilecode.io>"]

[tool.poetry.dependencies]
python = "*"
black = "20.8b1"
pytest = "6.1.0"
pytest-xdist = "2.1.0"
allure-pytest = "2.8.19"
mypy = "0.812"
playwright = "1.9.2"
requests = "2.24.0"
pillow = "8.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
