[tool.poetry]
name = "denise"
version = "0.2.1"
description = "A package containing love"
authors = ["Matthew Jones <you@example.com>"]
license = "MIT"
readme = "README.md"
keywords = ["love"]
include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
denise = 'denise.denise:start'
