[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "zoterosync"
author = "Marcelo Akira Inuzuka"
author-email = "marceloakira@ufg.br"
home-page = "https://gitlab.com/marceloakira/zoterosync"
classifiers= [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
description-file = "README.md"
requires = [
	"click",
	"pybtex>=0.24.0",
	"python-dotenv>=0.15.0",
	"python-rclone>=0.0.2"
]
requires-python = ">=3"

[tool.flit.scripts]
zoterosync = "zoterosync.zoterosync_cli:main"
