[project]
name = "askfm-api"
version = "0.2.1"
description = "Unofficial API wrapper for https://ask.fm"
readme = "README.md"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "Operating System :: OS Independent",]
dependencies = [ "requests~=2.25",]
requires-python = ">=3.9"
dynamic = [ "classifiers", "version",]
[[project.authors]]
name = "snowwm"
email = "snowwontmelt@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/AskfmForHumans/askfm-api"

[tool.isort]
profile = "black"
force_sort_within_sections = true
skip_gitignore = true

[tool.pdm.dev-dependencies]
dev = [ "black~=20.8b1", "isort~=5.7", "mypy~=0.812", "twine~=3.3",]
